import type { BlunData } from './types';

const now = Date.now();
const h = 3600_000;
const d = 24 * h;

export function seedData(): BlunData {
  return {
    contacts: [
      { id: 'c-mara', name: 'Mara', role: 'Product Design', hue: 262, avatar: 'v5', createdAt: now - 40 * d },
      { id: 'c-jonas', name: 'Jonas', role: 'Engineering', hue: 152, avatar: 'v6', createdAt: now - 38 * d },
      { id: 'c-priya', name: 'Priya', role: 'Customer Success', hue: 24, avatar: 'v3', createdAt: now - 31 * d },
      { id: 'c-theo', name: 'Theo', role: 'Sales', hue: 202, avatar: 'v8', createdAt: now - 22 * d },
      { id: 'c-ana', name: 'Ana', role: 'Marketing', hue: 330, avatar: 'v2', createdAt: now - 12 * d },
    ],
    features: [
      {
        id: 'f-onboarding',
        name: 'Onboarding flow',
        description: 'First-run experience and empty states',
        hue: 262,
        createdAt: now - 35 * d,
      },
      {
        id: 'f-search',
        name: 'Global search',
        description: 'Cmd+K search across everything',
        hue: 152,
        createdAt: now - 30 * d,
      },
      {
        id: 'f-exports',
        name: 'CSV exports',
        description: 'Export reports for finance',
        hue: 24,
        createdAt: now - 20 * d,
      },
      {
        id: 'f-darkmode',
        name: 'Dark mode',
        description: 'Theme switching and contrast pass',
        hue: 202,
        createdAt: now - 9 * d,
      },
    ],
    feedback: [
      {
        id: 'fb-1',
        text: 'The new onboarding checklist is genuinely delightful — three customers mentioned it unprompted this week.',
        kind: 'praise',
        status: 'new',
        source: 'call',
        priority: null,
        tags: ['customer-love', 'quote'],
        contactId: 'c-priya',
        featureId: 'f-onboarding',
        createdAt: now - 2 * h,
      },
      {
        id: 'fb-2',
        text: 'Search returns stale results after renaming a project. You have to hard-refresh to see the new name.',
        kind: 'issue',
        status: 'new',
        source: 'slack',
        priority: 'high',
        tags: ['bug', 'cache'],
        contactId: 'c-jonas',
        featureId: 'f-search',
        createdAt: now - 7 * h,
      },
      {
        id: 'fb-3',
        text: 'Could exports include the archived rows behind a toggle? Finance keeps asking for full history.',
        kind: 'idea',
        status: 'reviewed',
        source: 'meeting',
        priority: 'medium',
        tags: ['finance'],
        contactId: 'c-theo',
        featureId: 'f-exports',
        createdAt: now - 1 * d,
      },
      {
        id: 'fb-4',
        text: 'Dark mode charts still use the light gridlines — very low contrast on the dashboard.',
        kind: 'issue',
        status: 'reviewed',
        source: 'email',
        priority: null,
        tags: ['a11y', 'charts'],
        contactId: 'c-mara',
        featureId: 'f-darkmode',
        createdAt: now - 2 * d,
      },
      {
        id: 'fb-5',
        text: 'What if the empty inbox showed one keyboard shortcut a day? Small, but it would teach the product for free.',
        kind: 'idea',
        status: 'new',
        source: 'meeting',
        priority: 'low',
        tags: ['delight'],
        contactId: 'c-mara',
        featureId: 'f-onboarding',
        createdAt: now - 3 * d,
      },
      {
        id: 'fb-6',
        text: 'Demo went great — prospect said the search felt "instant". Worth quoting on the site.',
        kind: 'praise',
        status: 'done',
        source: 'call',
        priority: 'low',
        tags: ['quote', 'sales'],
        contactId: 'c-theo',
        featureId: 'f-search',
        createdAt: now - 4 * d,
      },
      {
        id: 'fb-7',
        text: 'The launch newsletter needs a screenshot of dark mode by Thursday — can we get a polished one?',
        kind: 'idea',
        status: 'done',
        source: 'slack',
        priority: 'high',
        tags: ['launch'],
        contactId: 'c-ana',
        featureId: 'f-darkmode',
        createdAt: now - 5 * d,
      },
      {
        id: 'fb-8',
        text: 'CSV export drops the timezone on timestamps. Two support tickets about it this month.',
        kind: 'issue',
        status: 'new',
        source: 'support',
        priority: 'high',
        tags: ['bug', 'data'],
        contactId: 'c-priya',
        featureId: 'f-exports',
        createdAt: now - 6 * d,
      },
    ],
  };
}
